---
- name: Set the Nuage config facts for Atomic master nodes
  set_fact:
    cert_output_dir: /var/usr/share/nuage-openshift-monitor
    kube_config: /var/usr/share/nuage-openshift-monitor/nuage.kubeconfig
    kubemon_yaml: /var/usr/share/nuage-openshift-monitor/nuage-openshift-monitor.yaml
    nuage_master_crt_dir: /var/usr/share/nuage-openshift-monitor/
    nuage_master_config_dsets_mount_dir: /var/usr/share/
    nuage_node_config_dsets_mount_dir: /var/usr/share/
    nuage_cni_bin_dsets_mount_dir: /var/opt/cni/bin
  when: master_host_type == "is_atomic"

- name: Create directory /usr/share/nuage-openshift-monitor
  become: yes
  file: path=/usr/share/nuage-openshift-monitor state=directory
  when: master_host_type == "is_rhel_server"

- name: Create directory /var/usr/share/nuage-openshift-monitor
  become: yes
  file: path=/var/usr/share/nuage-openshift-monitor state=directory
  when: master_host_type == "is_atomic"

- name: Create directory /var/usr/bin for monitor binary on atomic
  become: yes
  file: path=/var/usr/bin state=directory
  when: master_host_type == "is_atomic"

- name: Create CNI bin directory /var/opt/cni/bin
  become: yes
  file: path=/var/opt/cni/bin state=directory
  when: master_host_type == "is_atomic"

- name: Create the log directory
  become: yes
  file: path={{ nuage_mon_rest_server_logdir }} state=directory

- name: Download the certs and keys
  become: yes
  fetch: src={{ cert_output_dir }}/{{ item }} dest=/tmp/{{ item }} flat=yes
  with_items:
    - ca.crt
    - nuage.crt
    - nuage.key
    - nuage.kubeconfig

- name: Copy the certificates and keys
  become: yes
  copy: src="/tmp/{{ item }}" dest="{{ cert_output_dir }}/{{ item }}"
  with_items:
    - ca.crt
    - nuage.crt
    - nuage.key
    - nuage.kubeconfig

- include_tasks: certificates.yml

- name: Install Nuage VSD user certificate
  become: yes
  copy: src="{{ vsd_user_cert_file }}" dest="{{ cert_output_dir }}/{{ vsd_user_cert_file | basename }}"

- name: Install Nuage VSD user key
  become: yes
  copy: src="{{ vsd_user_key_file }}" dest="{{ cert_output_dir }}/{{ vsd_user_key_file | basename }}"

- name: Create Nuage master daemon set yaml file
  become: yes
  template: src=nuage-master-config-daemonset.j2 dest={{ cert_output_dir }}/nuage-master-config-daemonset.yaml owner=root mode=0644

- name: Create Nuage node daemon set yaml file
  become: yes
  template: src=nuage-node-config-daemonset.j2 dest={{ cert_output_dir }}/nuage-node-config-daemonset.yaml owner=root mode=0644

- name: Create Nuage Infra Pod daemon set yaml file
  become: yes
  template: src=nuage-infra-pod-config-daemonset.j2 dest={{ cert_output_dir }}/nuage-infra-pod-config-daemonset.yaml owner=root mode=0644

- name: Add the service account to the privileged scc to have root permissions for kube-system
  shell: oc adm policy add-scc-to-user privileged system:serviceaccount:kube-system:daemon-set-controller
  ignore_errors: true
  when: inventory_hostname == groups['masters'][0]

- name: Add the service account to the privileged scc to have root permissions for openshift-infra
  shell: oc adm policy add-scc-to-user privileged system:serviceaccount:openshift-infra:daemonset-controller
  ignore_errors: true
  when: inventory_hostname == groups['masters'][0]

- name: Spawn Nuage Master monitor daemon sets pod
  shell: oc create -f "{{ cert_output_dir }}"/nuage-master-config-daemonset.yaml
  ignore_errors: true
  when: inventory_hostname == groups['masters'][0]

- name: Spawn Nuage CNI daemon sets pod
  shell: oc create -f "{{ cert_output_dir }}"/nuage-node-config-daemonset.yaml
  ignore_errors: true
  when: inventory_hostname == groups['masters'][0]

- name: Spawn Nuage Infra daemon sets pod
  shell: oc create -f "{{ cert_output_dir }}"/nuage-infra-pod-config-daemonset.yaml
  ignore_errors: true
  when: inventory_hostname == groups['masters'][0]
