- name: Copy Nuage Master monitor daemon sets yaml to master node
  become: yes
  copy:
    src: nuage-master-config-daemonset.yaml
    dest: /etc/nuage-master-config-daemonset.yaml
    mode: 0755

- name: Spawn Nuage Master monitor daemon sets pod
  shell: kubectl create -f /etc/nuage-master-config-daemonset.yaml
  ignore_errors: true

- name: Copy Nuage node daemon sets yaml to master node
  become: yes
  copy:
    src: nuage-node-config-daemonset.yaml
    dest: /etc/nuage-node-config-daemonset.yaml
    mode: 0755

- name: Spawn Nuage node daemon sets pods
  shell: kubectl create -f /etc/nuage-node-config-daemonset.yaml
  ignore_errors: true
