---

- name: restart daemons
  command: /bin/true
  notify:
    - restart kubelet

- name: restart kubelet
  service: name=kubelet state=restarted
  ignore_errors: yes

- name: save iptables rules
  command: service iptables save
