kind: ConfigMap
apiVersion: v1
metadata:
  name: nuage-infra-test-config
  namespace: kube-system
data:
  # Name of the enterprise in which pods will reside
  enterprise_name: kubernetes
  # Name of the domain in which pods will reside
  domain_name: kubernetes
  # Name of the VSD user in admin group
  vsd_user: k8s-admin
  # pod network cidr that will be used
  pod_network_cidr: 70.70.0.0/16
  # vrs personality type
  personality: vrs

---

# This manifest installs Nuage Infra pod on
# each worker node in a Kubernetes cluster.
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: nuage-infra-test-ds
  namespace: kube-system
  labels:
    k8s-app: nuage-infra-test-ds
spec:
  selector:
    matchLabels:
      k8s-app: nuage-infra-test-ds
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: nuage-infra-test-ds
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
          operator: Exists
      containers:
        # This container spawns a Nuage Infra pod
        # on each worker node
        - name: install-nuage-infra-test
          image: nuage/infra:<nuage-release>
          command: ["/usr/bin/nuage-k8s-infra-pod.sh"]
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/log
              name: log-dir
            - mountPath: /var/run
              name: openvswitch-dir
          env:
            - name: VSP_ENTERPRISE
              valueFrom:
                configMapKeyRef:
                  name: nuage-infra-test-config
                  key: enterprise_name
            - name: VSP_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: nuage-infra-test-config
                  key: domain_name
            - name: VSP_USER
              valueFrom:
                configMapKeyRef:
                  name: nuage-infra-test-config
                  key: vsd_user
            - name: POD_NETWORK_CIDR
              valueFrom:
                configMapKeyRef:
                  name: nuage-infra-test-config
                  key: pod_network_cidr
            - name: PERSONALITY
              valueFrom:
                configMapKeyRef:
                  name: nuage-infra-test-config
                  key: personality
          lifecycle:
            preStop:
              exec:
                command: ["/usr/bin/nuage-k8s-infra-pod.sh", "-c"]
      volumes:
        - name: log-dir
          hostPath:
            path: /var/log
        - name: openvswitch-dir
          hostPath:
            path: /var/run
